name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: "Release tag used when publishing signed artifacts"
        required: true
        type: string

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag }}
